title:            富贵闲人
description:      orangeprince's blog.
canonical: http://orangeprince.info
# Owner/author information
owner:
  name:           orangeprince
  avatar:         avatar.png
  email:          orangeprince88@gmail.com
  dribbble:       coletownsend
  disqus:         orangeprince
  location:       "Shenzhen, China"
  # Plug in your disqus shortname!

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Links to include in top navigation
# For external links add external: true
links:
  - title: Essay
    url: /essay
  - title: Code
    url: /code
  - title: About
    url: /about
# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
highlighter: pygments
markdown:    redcarpet

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
    style: :compressed
# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:year/:month/:day/:title/

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
